Java中异常类

所有异常类的祖先是 `Throwable` 类，该类有两个子类，一个是`Error` 类，另一个是`Excption` 类

其中`Exception` 类是我们可以捕获的异常，`Error`类是会导致编译中断，如果`Exception` 异常不被捕获，也会导致程序编译中断

`Exception` 类的子类有`ClassNotFoundException` 等等

重点是两个错误

`StackOverFlowError` `（` 栈溢出 `）` 和  `OutOfMemoryError` 

如果线程请求的栈深度大于虚拟机所允许的最大深度，也就是栈帧的长度大于预期最大长度时，就会爆出 `StackOverFlowError`

如果虚拟机的栈内存允许动态扩展，当扩展栈容量无法申请到足够的内存是会爆出`OutOfMemoryError` 

这两个错误和Java的虚拟机栈有很大的关系 



`try-catch-finally` 关于 `finally` 里的代码块如何处理的问题，当`return ` 和 `finally` 相遇时，先处理`finally`, 然后再返回，当然`finally ` 代码块里的返回可以打断外面的返回，当`finally` 代码块第一行出现异常，`finally`里面的代码不会被执行完，`finally`代码块与`catch	` 关键字一样都是在抛出异常之后才会指向。

